server:
  port: 6666

spring:
  datasource:
    url: jdbc:mysql://124.221.219.86:3306/calculate?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8&useAffectedRows=true
    username: tq
    password: 83737328
    driver-class-name: com.mysql.cj.jdbc.Driver
    minimum-idle: 5
    # 池中最大连接数
    maximum-pool-size: 20
    ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
    hikari:
      auto-commit: true
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 600000
      pool-name: DatebookHikariCP
      ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      #数据库连接超时时间,默认30秒，即30000
      connection-timeout: 120000

minio:
  endPoint: http://124.221.219.86:19000
  accessKey: 1VZmSrKDODjDeKMT
  secretKey: NKus5htpps2yLykQQlu5KeAtxkuBou9E
  defaultBucket: test
  creativeBucket: creative

